/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alprueba;

/**
 *
 * @author Dary Castillo
 */
public enum Token {
   //SUSTANTIVO
  SUSTANTIVO,
  
  //ADJETIVOS
  ADJ_POSESIVO,
  ADJ_DEMOSTRATIVO,
  ADJ_CALIFICATIVO,
  ADJ_NUMERAL_CARDINAL,
  ADJ_NUMERAL_ORDINAL, 
  ADJ_INDEFINIDO,
  
  //ARTICULOS
  ART_DEFINIDO,
  ART_INDEFINIDO,
  
  //PRONOMBRES
  PRO_PERSONAL,
  PRO_NUMERAL,
  PRO_DEMOSTRATIVO,
  PRO_INTERROGATIVO,
  
 //VERBOS
  //VERBOS IRRREGULARES
  VER_IRREGULAR_INFINITO,
  VER_IRREGULAR_PASADOSIMPLE,
  VER_IRREGULAR_PASADOPARTICIPIO,
  
  //VERBOS REGULARES
  VERBO_REGULAR,
  
  //ADVERBIOS
  ADVIO_TIEMPO,
  ADVIO_LUGAR,
  ADVIO_CANTIDAD,
  ADVIO_MODO,
  ADVIO_AFIRMACION,
  ADVIO_NEGACION,
  ADVIO_DUDA,
  
  //PREPOSICION
  PREPOSICION, 
  
  //CONJUNCIONES, COORDINANTES
  CONJUN_COOR_COPULATIVA,
  CONJUN_COOR_ADVERSATIVA,
  CONJUN_COOR_DISTRIBUTIVA,
  CONJUN_COOR_DISYUNTIVA,
  CONJUN_COOR_EXPLICATIVA,
  
  //CONJUNCIONES, SUBORDIANTES
  CONJUN_SUBOR_CONDICIONAL,
  CONJUN_SUBOR_CAUSAL,
  CONJUN_SUBOR_CONSECUTIVA,
  CONJUN_SUBOR_CONSESIVA,
  CONJUN_SUBOR_COMPARATIVA,
  CONJUN_SUBOR_FINAL,
  
  //INTERJECCION
  INTERJECCION,
  CONTRACCION,
  //signos de puntuancion
  PUNTO, 
  COMA,
  PUNTOCOMA,
  DOSPUNTOS,
  INTERROGACIONABIERTO,
  INTERROGACIONCERRADO,
  ADMIRACIONABIERTO,
  ADMIRACIONCERRADO,
  PARENTESISABIERTO,
  PARENTESISCERRADO,
  CORCHETEABIERTO,
  CORCHETECERRADO,
  GUION,
  ASTERISCO,
  DIAGONAL,
  
  ERROR,
  PREGUNTA
    
}
